version: "3"

services:
    app:
        build: app
        expose:
            - "8000"
    proxy:
        build: proxy
        ports:
        - "80:80"
        volumes:
        - "./proxy/nginx.conf:/etc/nginx/nginx.conf:ro"
        - "./proxy/logs:/var/log/nginx"